#!/bin/bash
# The script for centos 6 minimal environment

if [ "$UID" -ne 0 ];then
	echo "must be run by root!"
	exit
fi

if [ "$#" -ne 1 ];then
	echo "Usage: $0 <package_name>"
	exit
fi


if [ -z `rpm -qa | grep epel-release` ];then
	yum install epel-release -y
fi


install_dep(){
	yum -y install unzip ntp wget rsync gcc gcc-c++ make autoconf libmcrypt libmcrypt-devel mcrypt mhash libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel libxml2 libxml2-devel zlib zlib-devel glibc glibc-devel glib2 glib2-devel bzip2 bzip2-devel ncurses ncurses-devel curl curl-devel e2fsprogs e2fsprogs-devel krb5-devel libidn libidn-devel openssl openssl-devel libtool libtool-libs libevent-devel libevent openldap openldap-devel openldap-clients openldap-servers libtool-ltdl libtool-ltdl-devel bison bison-devel cloog-ppl ppl libmemcached-devel expat-devel gettext-devel gd-devel mhash-devel pcre-devel screen boost boost-devel gperf libevent libevent-devel uuid-devel libuuid libuuid-devel uuid cmake geoip geoip-devel jemalloc jemalloc-devel tcl perl-ExtUtils-Embed

	if [ "$?" -eq 0 ];then
		echo "install dependent ... ok."
	else
		exit 1
	fi
}

install_mysql(){
if [ ! -d /data/lnmp/mysql ];then
	echo "download mysql ..."
	if [ ! -f ./mysql-5.6.26.tar.gz ];then
		wget http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.26.tar.gz
	fi
	echo "decompression ..."
	tar zxf mysql-5.6.26.tar.gz
	cd mysql-5.6.26
	echo "compile phase ..."
	cmake \
	-DCMAKE_INSTALL_PREFIX=/data/lnmp/mysql \
	-DMYSQL_DATADIR=/data/lnmp/mysql/var \
	-DSYSCONFDIR=/etc \
	-DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
	-DMYSQL_TCP_PORT=3306 \
	-DDEFAULT_CHARSET=utf8 \
	-DDEFAULT_COLLATION=utf8_general_ci \
	-DEXTRA_CHARSETS=all
	if [ "$?" -eq 0 ];then
		make -j4 && make install
	fi

	if [ ! `cat /etc/group | awk -F: '{print $1}'| grep mysql` ];then
		groupadd mysql
	fi
	if [ ! `cat /etc/passwd | awk -F: '{print $1}'| grep mysql` ];then
		useradd -M -g mysql -s /sbin/nologin mysql
	fi

	cp ../profile.d/mysql.sh /etc/profile.d/
	echo "/data/lnmp/mysql/lib" > /etc/ld.so.conf.d/mysql.conf
	ldconfig
	source /etc/profile.d/mysql.sh
	echo
	echo "init ..."
	echo
	mkdir /data/lnmp/mysql/var
	chown -R mysql:mysql /data/lnmp/mysql/var
	if [ -f /etc/my.cnf ];then
		rm -rf /etc/my.cnf
	fi
	/data/lnmp/mysql/scripts/mysql_install_db --user=mysql --basedir=/data/lnmp/mysql --datadir=/data/lnmp/mysql/var --explicit_defaults_for_times
	if [ "$?" -eq 0 ];then
		echo "init success."
	else
		exit 1
	fi
	cp  support-files/mysql.server  /etc/rc.d/init.d/mysqld
	cp ../conf/my.cnf /etc/
	chmod a+x /etc/rc.d/init.d/mysqld
	mkdir /data/lnmp/mysql_binlog
	mkdir /data/lnmp/mysql/logs
	chown -R mysql.mysql /data/lnmp/mysql/logs
	chown -R mysql.mysql /data/lnmp/mysql_binlog
	/etc/init.d/mysqld start
	chkconfig --add mysqld
	chkconfig mysqld on
else
		echo "mysql directory is exist. will be quit"
		exit 0
fi
}

install_php(){
if [ -d "/data/lnmp/php56" ];then
	echo "php directory is exist."
	exit 0
else
	if [ ! -f ./php-5.6.12.tar.gz ];then
		echo "download php ..."
		wget http://cn.php.net/get/php-5.6.12.tar.gz/from/this/mirror -O php-5.6.12.tar.gz
	fi
	echo "decompression ..."
	tar zxf php-5.6.12.tar.gz
	echo "compile phase ..."
	ln -s /usr/lib64/libldap* /usr/lib/
	ln -s /usr/lib64/libexpat* /usr/lib/
	cd php-5.6.12
	./configure --prefix=/data/lnmp/php56 \
	--with-zlib --with-mysql=mysqlnd --with-mysqli=mysqlnd \
	--with-pdo-mysql=mysqlnd --with-jpeg-dir --with-png-dir --with-freetype-dir \
	--with-libexpat-dir --with-libxml-dir --with-gd --with-openssl --with-iconv \
	--with-gettext --with-curl --with-mhash --enable-pcntl --with-mcrypt --with-bz2 \
	--with-ldap --enable-ftp --with-ldap-sasl --enable-gd-native-ttf \
	--enable-mbstring=all --enable-xml --enable-pdo --enable-exif --enable-mbregex \
	--enable-zip --enable-soap --enable-sockets --enable-bcmath --enable-shmop \
	--enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-inline-optimization \
	--disable-xmlreader --disable-debug --disable-rpath --without-pear \
	--enable-fpm --with-fpm-user=nobody --with-fpm-group=nobody --enable-opcache

	if [ "$?" -eq 0 ];then
		make && make install
	else
		exit 1
	fi
	cp php.ini-production /data/lnmp/php56/lib/php.ini
	cp -rf ../init/php-fpm /etc/init.d/
	chmod a+x /etc/init.d/php-fpm
	cp /data/lnmp/php56/etc/php-fpm.conf.default /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;pid = run\/php-fpm.pid/pid = run\/php-fpm.pid/' /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;error_log = log\/php-fpm.log/error_log = log\/php-fpm.log/' /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;daemonize = yes/daemonize = yes/' /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's#listen = 127.0.0.1:9000#listen = /data/lnmp/php56/var/run/php-fpm.sock#' /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;listen.owner = nobody/listen.owner = nobody/' /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;listen.group = nobody/listen.group = nobody/' /data/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;pm.max_requests = 500/pm.max_requests = 500/' /data/lnmp/php56/etc/php-fpm.conf
	sed '/; extension_dir = "ext"/ a\extension_dir = "/data/lnmp/php56/lib/php/extensions/no-debug-non-zts-20131226"\n\nzend_extension =opcache.so\nopcache.enable=1\nopcache.memory_consumption = 64\nopcache.interned_strings_buffer = 8\nopcache.max_accelerated_files = 4000\nopcache.revalidate_freq = 60\nopcache.fast_shutdown = 1\nopcache.enable_cli = 1\n' -i /data/lnmp/php56/lib/php.ini
	sed -i 's#expose_php = On#expose_php = Off#' /data/lnmp/php56/lib/php.ini
	sed -i 's#short_open_tag = Off#short_open_tag = On#' /data/lnmp/php56/lib/php.ini
	sed -i 's#;cgi.fix_pathinfo=1#cgi.fix_pathinfo=0#' /data/lnmp/php56/lib/php.ini
	sed -i 's#;always_populate_raw_post_data = -1#always_populate_raw_post_data = -1#' /data/lnmp/php56/lib/php.ini
	/etc/init.d/php-fpm start
	cp -rf ../profile.d/php.sh /etc/profile.d/
	source /etc/profile.d/php.sh
	chkconfig --add php-fpm
	chkconfig php-fpm on
fi
}

php_ext(){
	if [ ! -e ./igbinary-1.2.1.tgz ];then
        	wget http://pecl.php.net/get/igbinary-1.2.1.tgz
        fi
        tar zxvf igbinary-1.2.1.tgz
        cd igbinary-1.2.1
	/data/lnmp/php56/bin/phpize
	./configure  --enable-igbinary --with-php-config=/data/lnmp/php56/bin/php-config
        if [ $? -eq 0 ];then
        	make && make install && cd ..
        else
		exit 1
	fi

	if [ ! -e ./php-mongo-1.6.10.tgz ];then
		wget http://pecl.php.net/get/mongo-1.6.10.tgz -O php-mongo-1.6.10.tgz
	fi
	tar zxvf php-mongo-1.6.10.tgz
	cd mongo-1.6.10/
	/data/lnmp/php56/bin/phpize
	./configure --with-php-config=/data/lnmp/php56/bin/php-config --enable-mongo
	if [ "$?" -eq 0 ];then
		make && make install && cd ..
	else
		exit 1
	fi

	if [ ! -e ./php-redis-2.2.7.tgz ];then
		wget http://pecl.php.net/get/redis-2.2.7.tgz -O php-redis-2.2.7.tgz
	fi
	tar zxvf php-redis-2.2.7.tgz
	cd redis-2.2.7
	/data/lnmp/php56/bin/phpize
	./configure --with-php-config=/data/lnmp/php56/bin/php-config --enable-redis --enable-redis-igbinary
	if [ "$?" -eq 0 ];then
		make && make install && cd ..
	else
		exit 1
	fi

	if [ ! -e ./php-memcache-2.2.7.tgz ];then
		wget http://pecl.php.net/get/memcache-2.2.7.tgz -O php-memcache-2.2.7.tgz
	fi
	tar zxvf php-memcache-2.2.7.tgz
	cd memcache-2.2.7/
	/data/lnmp/php56/bin/phpize
	./configure --with-php-config=/data/lnmp/php56/bin/php-config  --enable-memcache
	if [ "$?" -eq 0 ];then
		make && make install && cd ..
	else
		exit 1
	fi

	sed '/opcache.enable_cli = 1/ a\[mongo]\nextension = mongo.so\n[redis]\nextension = redis.so\n[memcache]\nextension = memcache.so\n[igbinary]\nextension = igbinary.so' -i /data/lnmp/php56/lib/php.ini
	/etc/init.d/php-fpm restart

}

install_redis(){
if [ -d /data/lnmp/redis ];then
	echo "redis directory is exist."
else
	if [ ! -e './redis-2.8.22.tar.gz' ];then
		wget http://download.redis.io/releases/redis-2.8.22.tar.gz
	fi
	echo "install redis ..."
	tar zxvf redis-2.8.22.tar.gz
	cd redis-2.8.22
	make
	taskset -c 1 sudo make test
	if [ "$?" -eq 0 ];then
		mkdir -p /data/lnmp/redis/{logs,bin,data,conf,sbin,run}
		cd src
		cp redis-benchmark redis-check-aof redis-cli redis-sentinel redis-check-dump /data/lnmp/redis/bin/
		cp redis-server /data/lnmp/redis/sbin
		cd ..
		cp redis.conf /data/lnmp/redis/conf/6379.conf
		cp ../init/redis_6379 /etc/init.d/redis_6379
		sed -i 's/daemonize no/daemonize yes/' /data/lnmp/redis/conf/6379.conf
		sed -i 's#pidfile /var/run/redis.pid#pidfile /data/lnmp/redis/run/redis_6379.pid#' /data/lnmp/redis/conf/6379.conf
		sed -i 's#logfile ""#logfile "/data/lnmp/redis/logs/redis_6379.log"#' /data/lnmp/redis/conf/6379.conf
		sed -i 's#dbfilename dump.rdb#dbfilename 6379.rdb#' /data/lnmp/redis/conf/6379.conf
		sed -i 's#dir ./#dir /data/lnmp/redis/data#' /data/lnmp/redis/conf/6379.conf
		chmod a+x /etc/init.d/redis_6379
		/etc/init.d/redis_6379 start
		cp ../profile.d/redis.sh /etc/profile.d/
		source /etc/profile.d/redis.sh
	else
		exit 1
	fi
fi
}

install_mongo(){
if [ -d "/data/lnmp/mongo" ];then
	echo "mongo directory is exist."
else
	echo "install mongo ..."
	if [ ! -e "./mongodb-linux-x86_64-3.0.6.tgz" ];then
		wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.6.tgz
	fi
	tar zxvf mongodb-linux-x86_64-3.0.6.tgz
	mv mongodb-linux-x86_64-3.0.6 /data/lnmp/mongo
	mkdir /data/lnmp/mongo/{conf,data,logs}
	cp init/mongod /etc/init.d/mongod
	chmod a+x /etc/init.d/mongod
	cp conf/mongod.conf /data/lnmp/mongo/conf
	cp profile.d/mongo.sh /etc/profile.d/
	if [ ! `cat /etc/passwd | awk -F: '{print $1}'| grep mongod` ];then
		groupadd mongod && useradd -M -g mongod -s /sbin/nologin mongod
	fi
	chown -R mongod. /data/lnmp/mongo/logs
	chown -R mongod. /data/lnmp/mongo/data
	echo never > "/sys/kernel/mm/transparent_hugepage/enabled"
	echo never > "/sys/kernel/mm/transparent_hugepage/defrag"
	/etc/init.d/mongod start
	chkconfig --add mongod
	chkconfig mongod on
fi
}

install_nginx(){
if [ -d /data/lnmp/nginx ];then
	echo "openresty directory is exist."
else
	if [ ! `ls ./nginx-1.8.0.tar.gz` ];then
		wget http://nginx.org/download/nginx-1.8.0.tar.gz
	fi
	tar zxvf nginx-1.8.0.tar.gz
	cd nginx-1.8.0
	echo "install nginx ..."
	./configure --prefix=/data/lnmp/nginx --user=nobody \
	--group=nobody --with-ld-opt=-ljemalloc --with-http_ssl_module \
	--with-http_addition_module --with-http_sub_module --with-http_dav_module \
	--with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module \
	--with-http_perl_module --with-mail --with-mail_ssl_module --with-http_geoip_module \
	--with-http_realip_module

	if [ "$?" -eq 0 ];then
		make && make install
	else
		exit 1
	fi
	cp ../init/nginx /etc/init.d/nginx
	chmod a+x /etc/init.d/nginx
	mv /data/lnmp/nginx/conf/nginx.conf /data/lnmp/nginx/conf/nginx.conf.old
	cp ../conf/nginx.conf /data/lnmp/nginx/conf
	/bin/cp -rf ../conf/vhosts /data/lnmp/nginx/conf/
	/etc/init.d/nginx start
	chkconfig --add nginx
	chkconfig nginx on
fi
}
install_memcached(){
	if [ -d /data/lnmp/memcached ];then
		echo "memcached directory is exist."
	else
		if [ ! `ls ./memcached-1.4.24.tar.gz` ];then
			wget http://www.memcached.org/files/memcached-1.4.24.tar.gz
		fi
		tar zxvf memcached-1.4.24.tar.gz
		cd memcached-1.4.24
		echo "install memcache ..."
		./configure --prefix=/data/lnmp/memcached
		if [ "$?" -eq 0 ];then
			make && make install
		else
			exit 1
		fi
		cp ../init/memcached /etc/init.d/
		mkdir -p /data/lnmp/memcached/lock/subsys/
		mkdir /data/lnmp/memcached/run
		/etc/init.d/memcached start
	fi		
}
set_ulimit(){
	sed '/#@student        -       maxlogins       4/a\*\tsoft\tnofile\t65535\n*\thard\tnofile\t65535\n' -i /etc/security/limits.conf
	sed 's/*          soft    nproc     1024/*          soft    nproc     65535/' -i /etc/security/limits.d/90-nproc.conf
}


set_sysctl(){
	sed '$a\vm.swappiness = 0\nvm.overcommit_memory = 1\nnet.core.somaxconn = 512\nnet.ipv4.tcp_tw_reuse = 1\nnet.ipv4.tcp_tw_recycle = 1\nnet.ipv4.tcp_fin_timeout = 30\nnet.ipv4.tcp_keepalive_time = 1200\nnet.ipv4.ip_local_port_range = 1024 65535\nnet.ipv4.tcp_max_syn_backlog = 4096\nnet.ipv4.tcp_max_tw_buckets = 5000\nnet.ipv4.tcp_synack_retries = 2\nnet.ipv6.conf.default.disable_ipv6 = 1\nnet.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv4.conf.default.arp_announce = 2\nnet.core.wmem_max = 873200\nnet.core.rmem_max = 873200\nnet.ipv4.tcp_wmem = 8192 436600 873200\nnet.ipv4.tcp_rmem = 32768 436600 873200\nnet.ipv4.tcp_mem = 786432 1048576 1572864\nnet.ipv4.tcp_retries2 = 5\n' -i /etc/sysctl.conf
	sysctl -p
}

set_ntp(){
	yum install ntp -y
	sed -i 's/server 0.centos.pool.ntp.org iburst/#server 0.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i 's/server 1.centos.pool.ntp.org iburst/#server 1.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i 's/server 2.centos.pool.ntp.org iburst/#server 2.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i 's/server 3.centos.pool.ntp.org iburst/#server 3.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i '/#server 3.centos.pool.ntp.org iburst/a\server 0.th.pool.ntp.org\nserver 1.asia.pool.ntp.org\nserver 2.asia.pool.ntp.org\n' /etc/ntp.conf
	/etc/init.d/ntpd start
	ntpdate
}

case "$1" in
	dep)
	install_dep
	;;
	nginx)
	install_nginx
	;;
	ulimit)
	set_ulimit
	;;
	mysql)
	install_mysql
	;;
	php)
	install_php
	;;
	redis)
	install_redis
	;;
	mongo)
	install_mongo
	;;
	php-ext)
	php_ext
	;;
	sysctl)
	set_sysctl
	;;
	ntp)
	set_ntp
	;;
	memcached)
	install_memcached
	;;
	*)
	echo "error flag!"
	;;
esac
